version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-trust}
      POSTGRES_USER: ${POSTGRES_USER:-trust}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-trust}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-trust}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data --address :9000 --console-address :9001
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-dev}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-devpass}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  redis_data:
  minio_data: